# see https://github.com/compose-spec/compose-spec/blob/master/spec.md
# see https://github.com/opencontainers/image-spec/blob/master/annotations.md
services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 8025:8025
    networks:
      default:
        aliases:
          - mail.test
  wso2am:
    build:
      context: wso2am
    ports:
      - 9443:9443 # api management.
      - 8243:8243 # api gateway (https).
      - 8280:8280 # api gateway (http).
      - 8099:8099 # api gateway (wss).
      - 9099:9099 # api gateway (ws).
    restart: on-failure
    volumes:
      - ./wso2am/deployment.toml:/wso2am/repository/conf/deployment.toml:ro
      - wso2am-database:/wso2am/repository/database
    depends_on:
      - mailhog
    networks:
      default:
        aliases:
          - wso2am.test
  init:
    depends_on:
      - mailhog
      - wso2am
    build:
      context: init
    volumes:
      - .:/host
  example-go:
    restart: on-failure
    build:
      context: services/example-go
    ports:
      - 8000:8000
    networks:
      default:
        aliases:
          - example-go.test
volumes:
  wso2am-database:
