# see https://github.com/compose-spec/compose-spec/blob/master/spec.md
# see https://github.com/opencontainers/image-spec/blob/master/annotations.md
services:
  bootstrap:
    build:
      context: bootstrap
    volumes:
      - .:/host
  mail:
    image: axllent/mailpit:v1.23.1
    ports:
      - 8025:8025
    restart: on-failure
    networks:
      default:
        aliases:
          - mail.test
  wso2am:
    build:
      context: wso2am
    ports:
      - 9443:9443 # management (https).
      - 8243:8243 # gateway (https).
      - 8280:8280 # gateway (http).
      - 8099:8099 # gateway (wss).
      - 9099:9099 # gateway (ws).
    restart: on-failure
    volumes:
      - ./wso2am/deployment.toml:/home/wso2carbon/wso2-config-volume/repository/conf/deployment.toml:ro
      - ./tmp/wso2am-ca/wso2am-keystore.p12:/home/wso2carbon/wso2-config-volume/repository/resources/security/wso2am-keystore.p12:ro
      - ./tmp/wso2am-ca/wso2am-truststore.p12:/home/wso2carbon/wso2-config-volume/repository/resources/security/wso2am-truststore.p12:ro
      - wso2am-database:/home/wso2carbon/wso2am-4.5.0/repository/database
    depends_on:
      bootstrap:
        condition: service_completed_successfully
      mail:
        condition: service_healthy
    networks:
      default:
        aliases:
          - wso2am.test
  init:
    depends_on:
      wso2am:
        condition: service_healthy
    build:
      context: init
    volumes:
      - ./tmp/wso2am-ca/wso2am-ca-crt.pem:/usr/local/share/ca-certificates/wso2am-ca.crt:ro
      - .:/host
  example-go:
    restart: on-failure
    build:
      context: services/example-go
    ports:
      - 8000:8000
    networks:
      default:
        aliases:
          - example-go.test
volumes:
  wso2am-database:
